name: React CI/CD with Format, Lint, Test(smoke test), Build, Deploy, and Review

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize]

permissions:
    contents: write
    pull-requests: write

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: GitHub에서 코드 내려받기
              uses: actions/checkout@v3

            - name: Node 버전 설치 및 설정
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: 의존성 설치
              run: npm ci

            - name: 코드 포맷 일치
              run: npm run format

            - name: 코드 오류 검사
              run: npm run lint

            - name: 빌드 (only on push)
              if: github.event_name == 'push'
              run: npm run build

            - name: Netlify에 배포
              uses: nwtgck/actions-netlify@v2.0
              with:
                  publish-dir: ./build
                  production-branch: main
                  deploy-message: "GitHub Actions Deploy"


            - name: Run AI Code Review (only on PR)
              if: github.event_name == 'pull_request'
              uses: dann0316/ai-code-reviewer@main
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  OPENAI_API_MODEL: "gpt-4"
                  exclude: "**/*.json, **/*.md"

