name: React CI/CD with Format, Lint, Build, and Review (Test, Deploy는 아직)

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize]

permissions:
    contents: write
    pull-requests: write

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Dependencies
              run: npm ci

            - name: Run Prettier
              run: npm run format

            - name: Run ESLint
              run: npm run lint

            - name: Build (only on push)
              if: github.event_name == 'push'
              run: npm run build

            - name: Run AI Code Review (only on PR)
              if: github.event_name == 'pull_request'
              uses: dann0316/ai-code-reviewer@main
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  OPENAI_API_MODEL: "gpt-4"
                  exclude: "**/*.json, **/*.md"

                  # deploy,test 코드 작성
                  