# name: React CI/CD with Format, Lint, Deploy (Test아직)

# on:
#   push:
#     branches:
#       - main # main 브랜치에 push될 때만 실행

# jobs:
#   build-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: GitHub에서 코드 내려받기
#         uses: actions/checkout@v3

#       - name: Node 버전(18) 설치 및 설정
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: 의존성 패키지 설치
#         run: npm ci

#       - name: 빌드
#         run: npm run build

#       - name: Netlify에 배포
#         uses: nwtgck/actions-netlify@v1.2.4
#         with:
#           publish-dir: ./dist
#           production-branch: main
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           deploy-message: "GitHub Actions Deploy"
#           # netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#           # netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
